// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pyoxrmczifzwftnolqlf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5b3hybWN6aWZ6d2Z0bm9scWxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MDQxODcsImV4cCI6MjA2OTQ4MDE4N30.RJyr_97EwxbevyysR4HlFg_ejJKqe3IQYhIPHVZVQTs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});